# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40217c923b694b0959ef3c2b73b88837f6cc9ebec3147e0ee2c29dc793a673888632b7d6fc9d07aa114b75efb520d40a62343d5ff4dba5401ad3ea81a4c94eda

test:
  secret_key_base: 1e82dab50df6af22a029380a67e2b7b9a98c4a975c1723d8f96db29d9a2a55751b1cf00abbb3f203f737a097cea69c3ef936ab5165d7439cd612447866aa900f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
